meiduo_mall/meiduo_mall/apps/areas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^areas/$', views.AreaView.as_view()),
]

meiduo_mall/meiduo_mall/apps/carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^carts/$', views.CartView.as_view()),
    url('^carts/selection/$', views.CartSelectionView.as_view()),
    url('^carts/simple/$', views.CartSimpleView.as_view()),
]

meiduo_mall/meiduo_mall/apps/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$', views.ListView.as_view()),
    url('^hot/(?P<category_id>\d+)/$', views.HotView.as_view()),
    url(r'^detail/(?P<sku_id>\d+)/$', views.DetailView.as_view()),
    url(r'^detail/visit/(?P<category_id>\d+)/$', views.DetailVisitView.as_view()),
    url('^browse_histories/$', views.HistoryView.as_view()),
]

meiduo_mall/meiduo_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls')),
    url('^', include('verifycations.urls')),
    url('^', include('contents.urls')),
    url('^', include('oauth.urls')),
    url('^', include('areas.urls')),
    url('^', include('goods.urls')),
    # url(r'^search/', include('haystack.urls')),
    url('^', include('carts.urls')),
    url('^', include('orders.urls')),
    url('^', include('payments.urls')),
    url('^meiduo_admin/', include('meiduo_admin.urls')),


    url('^docs/', include_docs_urls(title='meiduo_mall')),

]

meiduo_mall/meiduo_mall/apps/areas/models.py
from django.db import models


class Area(models.Model):
    name = models.CharField(max_length=20)
    # 自关联，允许为空，表示关联对象
    parent = models.ForeignKey('self', null=True, blank=True, related_name='subs')
    #django框架根据外键parent自动创建：parent_id===》关联对象的主键

    class Meta:
        db_table = 'tb_areas'

    def __str__(self):
        return self.name

meiduo_mall/meiduo_mall/apps/carts/models.py
# from django.db import models
#
# # Create your models here.
#
#
# # class BookSerialzier():
# #
# #     heroinfo_set
#
# class Bookinfo(models.Model):
#
#     btitl=models.CharField(max_length=11)
#
#
# class BassModel(models.Model):
#     create_time=models.DateField()
#
# class HeroInfo(BassModel):
#
#     book=models.ForeignKey(Bookinfo,on_delete=models.SET_DEFAULT,default='',related_name='hero')
#
#     class Meta:
#         db_table='tb_book'
#         ordering=('-id')
#
#
#
#     def change_data(self):
#         print(11111)
#
#
# # Bookinfo().heroinfo_set.all()
# Bookinfo().hero.all()
#
#
# HeroInfo().change_data()
#
# HeroInfo().Meta.db_table
#
#

meiduo_mall/meiduo_mall/apps/contents/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel


class ContentCategory(BaseModel):
    """广告内容类别"""
    name = models.CharField(max_length=50, verbose_name='名称')
    key = models.CharField(max_length=50, verbose_name='类别键名')

    class Meta:
        db_table = 'tb_content_category'
        verbose_name = '广告内容类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Content(BaseModel):
    """广告内容"""
    category = models.ForeignKey(ContentCategory, on_delete=models.PROTECT, verbose_name='类别')
    title = models.CharField(max_length=100, verbose_name='标题')
    url = models.CharField(max_length=300, verbose_name='内容链接')
    image = models.ImageField(null=True, blank=True, verbose_name='图片')
    text = models.TextField(null=True, blank=True, verbose_name='内容')
    sequence = models.IntegerField(verbose_name='排序')
    status = models.BooleanField(default=True, verbose_name='是否展示')

    class Meta:
        db_table = 'tb_content'
        verbose_name = '广告内容'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name + ': ' + self.title

meiduo_mall/meiduo_mall/apps/goods/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel


class GoodsCategory(BaseModel):

    """商品类别

        上一级查询下一级数据相当于是主表查询副表
        下一级查询上一级数据相当于是副表查询主表
    """
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    # a=models.OneToOneField('',related_name='')
    # a=models.ManyToManyField('',related_name='')
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, related_name='channels', on_delete=models.CASCADE,
                                 verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, related_name='skus', on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    # category_id====>category对象的id
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)

class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name


# SPU().objects.aggregate()

meiduo_mall/meiduo_mall/apps/meiduo_admin/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/oauth/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel
from users.models import User

class OAuthQQUser(BaseModel):
    """QQ登录用户数据"""
    # user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='用户')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    openid = models.CharField(max_length=64, verbose_name='openid', db_index=True)

    class Meta:
        db_table = 'tb_oauth_qq'
        verbose_name = 'QQ登录用户数据'
        verbose_name_plural = verbose_name

meiduo_mall/meiduo_mall/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from .models import Area
from django import http
from meiduo_mall.utils.response_code import RETCODE
from django.core.cache import cache
from . import constants


class AreaView(View):
    def get(self, request):
        area_id = request.GET.get('area_id')
        if area_id is None:
            # 先获取缓存，如果存在中不存在，再查询mysq并缓存
            result = cache.get('province_list')
            if result is None:
                # 没有传递地区编号，表示查询省列表
                province_list = Area.objects.filter(parent__isnull=True)
                # 只返回地区对象的编号、名称
                province_list2 = []
                for province in province_list:
                    province_list2.append({
                        'id': province.id,
                        'name': province.name
                    })

                result = {
                    'code': RETCODE.OK,
                    'errmsg': "OK",
                    'province_list': province_list2
                }
                cache.set('province_list', result, constants.AREA_CACHE_EXPIRES)

            return http.JsonResponse(result)
        else:
            result = cache.get('area_' + area_id)
            if result is None:
                # 有地区编号，表示查询指定地区的子级地区列表
                try:
                    area = Area.objects.get(pk=area_id)
                except:
                    return http.JsonResponse({'code': RETCODE.PARAMERR, 'errmsg': '地区编号无效'})
                # 获取指定地区的子级地区
                sub_list = area.subs.all()
                # 整理前端需要的数据格式
                sub_list2 = []
                for sub in sub_list:
                    sub_list2.append({
                        'id': sub.id,
                        'name': sub.name
                    })

                result = {
                    'code': RETCODE.OK,
                    'errmsg': 'OK',
                    'sub_data': {
                        'id': area.id,
                        'name': area.name,
                        'subs': sub_list2
                    }
                }
                cache.set('area_' + area_id, result, constants.AREA_CACHE_EXPIRES)

            return http.JsonResponse(result)

meiduo_mall/meiduo_mall/apps/contents/views.py
from django.shortcuts import render
from django.views import View
from goods.models import GoodsCategory, GoodsChannel
from .models import ContentCategory, Content
from meiduo_mall.utils.categories import get_categories

class IndexView(View):
    def get(self, request):
        #查询分类
        categories=get_categories()

        # 查询广告数据
        content_category_list = ContentCategory.objects.all()
        # 构造广告字典
        '''
        {广告位标识：[广告1,....]}
        '''
        contents = {}
        for content_category in content_category_list:
            contents[content_category.key] = content_category.content_set.order_by('sequence')

        context = {
            'categories': categories,
            'contents': contents
        }

        return render(request, 'index.html', context=context)

meiduo_mall/meiduo_mall/apps/meiduo_admin/views/images.py
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from goods.models import SKUImage, SKU
from meiduo_admin.serializers.images import SKUImageSerializer, SKUSerializer
from meiduo_admin.utils import PageNum


class ImageView(ModelViewSet):

    queryset = SKUImage.objects.all()
    serializer_class = SKUImageSerializer
    pagination_class = PageNum
    permission_classes = [IsAdminUser]

    def simple(self, request):

        skus = SKU.objects.all()
        ser = SKUSerializer(skus, many=True)
        return Response(ser.data)

meiduo_mall/meiduo_mall/apps/meiduo_admin/views/option.py
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from goods.models import SpecificationOption
from meiduo_admin.serializers.option import SpecificationOptionSerializer
from meiduo_admin.utils import PageNum


class OptionView(ModelViewSet):

    queryset = SpecificationOption.objects.all()

    serializer_class = SpecificationOptionSerializer

    pagination_class = PageNum

    permission_classes = [IsAdminUser]

    def simple(self, request):

        options = SpecificationOption.objects.all()
        ser = SpecificationOptionSerializer(options, many=True)

        return Response(ser.data)

meiduo_mall/meiduo_mall/apps/meiduo_admin/views/skus.py
from rest_framework.decorators import action
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from goods.models import SPUSpecification, SKU, GoodsCategory, SpecificationOption
from meiduo_admin.serializers.skus import SKUSerializer, GoodsCategorySerializer, \
    SPUSpecificationSerializer
from meiduo_admin.utils import PageNum


class SKUView(ModelViewSet):

    queryset = SKU.objects.all()
    serializer_class = SKUSerializer
    pagination_class = PageNum
    permission_classes = [IsAdminUser]


    # 重写get_queryset方法，根据前端是否传递keyword值返回不同查询结果
    def get_queryset(self):
        # 获取前端传递的keyword值
        keyword = self.request.query_params.get('keyword')
        # 如果keyword是空字符，则说明要获取所有用户数据
        if keyword is '' or keyword is None:
            return SKU.objects.all()
        else:
            return SKU.objects.filter(name__contains= keyword)

    @action(methods=['get'], detail=False)
    def categories(self, request):

        data = GoodsCategory.objects.filter(subs=None)

        ser = GoodsCategorySerializer(data, many=True)

        return Response(ser.data)

    def specs(self, request, pk):

        data = SPUSpecification.objects.filter(spu_id=pk)

        ser = SPUSpecificationSerializer(data, many=True)

        return Response(ser.data)

meiduo_mall/meiduo_mall/apps/meiduo_admin/views/specs.py
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from goods.models import SPUSpecification, SPU
from meiduo_admin.serializers.specs import SPUSpecificationSerializer, SPUSerializer
from meiduo_admin.utils import PageNum


class SpecsView(ModelViewSet):

    queryset = SPUSpecification.objects.all()

    serializer_class = SPUSpecificationSerializer

    pagination_class = PageNum

    permission_classes = [IsAdminUser]

    def simple(self, request):

        spus = SPU.objects.all()
        ser = SPUSerializer(spus, many=True)

        return Response(ser.data)

meiduo_mall/meiduo_mall/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-购物车</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
	<script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
</head>
<body>
	<div id="app" v-cloak>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到美多商城!</div>
			<div class="fr">
            <div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="/static/user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_wrap fl">
			<form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
			<ul class="search_suggest fl">
				<li><a href="#">索尼微单</a></li>
				<li><a href="#">优惠15元</a></li>
				<li><a href="#">美妆个护</a></li>
				<li><a href="#">买2免1</a></li>
			</ul>
		</div>
	</div>

	<div class="total_count">全部商品<em>[[total_count]]</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

	<ul class="cart_list_td clearfix" v-for="(sku,index) in carts">
		<li class="col01"><input type="checkbox" name="selected" v-model="sku.selected" @change="update_selected(index)"></li>
		<li class="col02"><img :src="sku.default_image_url"></li>
		<li class="col03">[[sku.name]]</li>
		<li class="col04">台</li>
		<li class="col05">[[sku.price]]元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" @click="on_add(index)">+</a>
				<input type="text" class="num_show fl" v-model="sku.count" autocomplete="off" @blur="on_input(index)">
				<a href="javascript:;" class="minus fl" @click="on_minus(index)">-</a>
			</div>
		</li>
		<li class="col07">[[sku.total_amount]]元</li>
		<li class="col08"><a href="javascript:;" @click="on_delete(index)">删除</a></li>
	</ul>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="selected_all" :checked="selected_all" @change="on_selected_all"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>[[total_selected_amount]]</em><br>共计<b>[[total_selected_count]]</b>件商品</li>
		<li class="col04"><a href="/orders/settlement/">去结算</a></li>
	</ul>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	</div>
	<script>
        var cart_skus = {{ cart_skus|safe }};
    </script>
    <script type="text/javascript" src="/static/js/common.js"></script>
	<script type="text/javascript" src="/static/js/cart.js"></script>
</body>
</html>

meiduo_mall/meiduo_mall/templates/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-订单确认</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
    <script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
</head>
<body>
<div id="app" v-cloak>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到美多商城!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em>张 山</em>
                </div>
                <div class="login_btn fl">
                    <a href="login.html">登录</a>
                    <span>|</span>
                    <a href="register.html">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="user_center_info.html">用户中心</a>
                    <span>|</span>
                    <a href="cart.html">我的购物车</a>
                    <span>|</span>
                    <a href="/static/user_center_order.html">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>

    <h3 class="common_title">确认收货地址</h3>

    <div class="common_list_con clearfix" id="get_site">
        <dl>
            <dt>寄送到：</dt>
            {% for address in addresses %}
                <dd><input type="radio" name="address_id" v-model="nowsite" value="{{ address.id }}"
                        {% if address.id == request.user.default_address_id %} checked="checked"{% endif %}>
                    {{ address.province.name }}
                    {{ address.city.name }}
                    {{ address.district.name }}
                    {{ address.detail_address }}
                    （{{ address.receiver }} 收） {{ address.mobile }}
                </dd>
            {% endfor %}
        </dl>
        <a href="/addresses/" class="edit_site">编辑收货地址</a>
    </div>

    <h3 class="common_title">支付方式</h3>
    <div class="common_list_con clearfix">
        <div class="pay_style_con clearfix">
            <input type="radio" name="pay_method" value="1" v-model="pay_method">
            <label class="cash">货到付款</label>
            <input type="radio" name="pay_method" value="2" v-model="pay_method" checked="checked">
            <label class="zhifubao"></label>
        </div>
    </div>

    <h3 class="common_title">商品列表</h3>

    <div class="common_list_con clearfix">
        <ul class="goods_list_th clearfix">
            <li class="col01">商品名称</li>
            <li class="col02">商品单位</li>
            <li class="col03">商品价格</li>
            <li class="col04">数量</li>
            <li class="col05">小计</li>
        </ul>

        {% for sku in sku_list %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ loop.index }}</li>
                <li class="col02"><img src="{{ sku.default_image_url }}"></li>
                <li class="col03">{{ sku.name }}</li>
                <li class="col04">台</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">{{ sku.count }}</li>
                <li class="col07">{{ sku.total_amount }}元</li>
            </ul>
        {% endfor %}
    </div>

    <h3 class="common_title">总金额结算</h3>

    <div class="common_list_con clearfix">
        <div class="settle_con">
            <div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_amount }}元</b></div>
            <div class="transit">运费：<b>{{ transit }}元</b></div>
            <div class="total_pay">实付款：<b>{{ payment_amount }}元</b></div>
        </div>
    </div>

    <div class="order_submit clearfix">
        <a href="javascript:;" id="order_btn" @click="on_order_submit">提交订单</a>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript">
    let payment_amount ={{ payment_amount }};
    let default_address_id = {{ request.user.default_address_id }}
</script>
<script type="text/javascript" src="/static/js/common.js"></script>
<script type="text/javascript" src="/static/js/place_order.js"></script>
</body>
</html>